sl_tom/urls.py
from django.urls import path, include

urlpatterns = [
    path("", include("tom_common.urls")),
    path("zooniverse/", include("zooniverse.urls", namespace="zooniverse")),
]

zooniverse/urls.py
from django.urls import path, include

from zooniverse.views import (
    ZooniverseTargetListView,
    ZooniverseTargetDetailView,
)

app_name = "zooniverse"

urlpatterns = [
    path("", ZooniverseTargetListView.as_view(), name="index"),
    path("targets", ZooniverseTargetListView.as_view(), name="zooniversetarget_list"),
    path(
        "targets/<int:pk>/",
        ZooniverseTargetDetailView.as_view(),
        name="zooniversetarget_detail",
    ),
]

zooniverse/models.py
from astropy import units

from collections import Counter

from django.core.files.base import ContentFile
from django.db import models
from django.db.models import Count
from django.urls import reverse

from lightkurve.io.tess import read_tess_lightcurve

from matplotlib import pyplot

from zooniverse.client import project
from zooniverse.lightcurve import generate_image


def fetch_tess_data(data_uri):
    try:
        ts = read_tess_lightcurve(data_uri)
    except (FileNotFoundError, ValueError, TypeError):
        return None
    # Trim the first few hours from the start as loads of SPOC light curves seem to start with spurious peaks
    ts = ts[ts["time"] > ts["time"][0] + 3 * units.hour]
    return ts


class ZooniverseSurvey(models.Model):
    TESS = "TESS"
    FETCH_DATA_CHOICES = ((TESS, "TESS"),)
    FETCH_DATA_METHODS = {
        TESS: fetch_tess_data,
    }

    name = models.CharField(max_length=50)

    fetch_data_method = models.CharField(
        max_length=10, choices=FETCH_DATA_CHOICES, null=True, blank=True
    )

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def fetch_data(self, data_uri):
        if not self.fetch_data_method:
            return None
        return self.FETCH_DATA_METHODS[self.fetch_data_method](data_uri)


def zooniversetarget_lightcurve_image_path(instance, filename):
    return f"target_lightcurves/{str(instance.pk)[:3]}/{instance.pk}/{filename}"


class ZooniverseTarget(models.Model):
    survey = models.ForeignKey(ZooniverseSurvey, on_delete=models.CASCADE)
    identifier = models.CharField(max_length=128)

    generated_lightcurve_image = models.ImageField(
        null=True, upload_to=zooniversetarget_lightcurve_image_path
    )

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.survey} {self.identifier}"

    def aggregated_annotations(self):
        tr = self.zooniversetargetreduction_set.order_by("-created").first()
        if tr is None:
            return None
        return tr.reduced_annotations

    def annotations(self):
        return self.classifications().values_list("annotation", flat=True)

    def classifications(self):
        return ZooniverseClassification.objects.filter(
            subject_id__in=self.zooniversesubject_set.all().values_list("pk", flat=True)
        )

    @property
    def data_url(self):
        return self.zooniversesubject_set.all().first().data_url

    def fetch_data(self):
        return self.survey.fetch_data(self.data_url)

    def generate_lightcurve_image(self):
        annotations = self.aggregated_annotations()
        if annotations and len(annotations) > 0:
            highlights = list(
                zip(annotations["x_min"], annotations["x_mid"], annotations["x_max"])
            )
        else:
            highlights = None
        data = self.fetch_data()
        if data is None:
            return
        fig = generate_image(
            data,
            highlights=highlights,
        )
        image_data = ContentFile(b"")
        try:
            fig.savefig(image_data)
        except:
            pass
        else:
            self.generated_lightcurve_image.save(
                "lightcurve.png", image_data, save=True
            )
        finally:
            pyplot.close(fig=fig)

    def get_absolute_url(self):
        return reverse("zooniverse:zooniverse_target_detail", args=[str(self.pk)])

    @property
    def lightcurve_image(self):
        if not self.generated_lightcurve_image:
            self.generate_lightcurve_image()
        if self.generated_lightcurve_image:
            return self.generated_lightcurve_image
        return None


class ZooniverseSubjectSet(models.Model):
    subject_set_id = models.IntegerField()

    @classmethod
    def active(cls):
        return cls.objects.filter(
            pk__in=ZooniverseSubject.objects.filter(retired_at=None)
            .values_list("subject_set_id", flat=True)
            .distinct()
        )

    def active_subjects(self):
        return self.zooniversesubject_set.exclude(retired_at=None)

    def retired_subjects(self):
        return self.zooniversesubject_set.filter(retired_at=None)

    def classification_count_distribution(self):
        subjects = self.zooniversesubject_set.annotate(
            num_classifications=Count("zooniverseclassification")
        )

        distribution = Counter(
            dict(subjects.values_list("subject_id", "num_classifications")).values()
        )
        return distribution


class ZooniverseSubject(models.Model):
    subject_id = models.BigIntegerField(unique=True)
    subject_set = models.ForeignKey(
        ZooniverseSubjectSet, null=True, blank=True, on_delete=models.CASCADE
    )
    target = models.ForeignKey(ZooniverseTarget, on_delete=models.CASCADE)

    sequence = models.CharField(
        max_length=50, null=True, blank=True, help_text="Sector, data release, etc."
    )
    data_url = models.URLField(null=True, blank=True)
    start_time = models.DateTimeField(
        null=True, blank=True, help_text="Earliest time in the light curve"
    )
    end_time = models.DateTimeField(
        null=True, blank=True, help_text="Latest time in the light curve"
    )

    metadata = models.JSONField()

    retired_at = models.DateTimeField(null=True, blank=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def talk_url(self):
        return f"https://www.zooniverse.org/projects/{project.slug}/talk/subjects/{self.subject_id}"

    @property
    def annotations(self):
        return self.zooniverseclassification_set.values_list("annotation", flat=True)

    @property
    def annotation_count(self):
        return len(self.annotations)


class ZooniverseClassification(models.Model):
    classification_id = models.BigIntegerField(unique=True)
    subject = models.ForeignKey(ZooniverseSubject, on_delete=models.CASCADE)

    user_id = models.BigIntegerField(null=True, blank=True)
    timestamp = models.DateTimeField()
    annotation = models.JSONField()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


class ZooniverseTargetReduction(models.Model):
    """
    Reduced classifications for targets.
    """

    target = models.ForeignKey(ZooniverseTarget, on_delete=models.CASCADE)
    classifications = models.ManyToManyField(ZooniverseClassification)

    reduced_annotations = models.JSONField()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

zooniverse/forms.py
from django import forms


class TargetLookupForm(forms.Form):
    search = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Target or subject ID"})
    )

zooniverse/views.py
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from django.contrib.auth.mixins import LoginRequiredMixin

from zooniverse.forms import TargetLookupForm
from django.shortcuts import redirect
from zooniverse.models import (
    ZooniverseTarget,
)


class ZooniverseTargetDetailView(LoginRequiredMixin, DetailView):
    model = ZooniverseTarget


class ZooniverseTargetListView(LoginRequiredMixin, ListView):
    model = ZooniverseTarget

    def render_to_response(self, context, **response_kwargs):
        queryset = context.get("object_list", self.get_queryset())
        if queryset.count() == 1:
            print(queryset)
            obj = list(queryset)[0]  # Calling .first() fails
            return redirect("zooniverse:zooniversetarget_detail", pk=obj.pk)
        return super().render_to_response(context, **response_kwargs)

    paginate_by = 50

    def get_queryset(self):
        queryset = super().get_queryset()
        search = self.request.GET.get("search")
        if search:
            queryset = queryset.filter(identifier__icontains=search) | queryset.filter(
                zooniversesubject__subject_id__icontains=search
            )
            queryset = queryset.distinct()

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["target_lookup_form"] = TargetLookupForm(
            initial={"search": self.request.GET.get("search", "")}
        )
        return context

zooniverse/templates/zooniverse/zooniversetarget_detail.html
{% extends "tom_common/base.html" %}

{% block content %}
<h1>Zooniverse Target Detail</h1>

<div>
    <h2>{{ object.identifier }}</h2>
    <ul>
        <li><strong>Survey:</strong> {{ object.survey }}</li>
        <li><strong>Created:</strong> {{ object.created }}</li>
        <li><strong>Updated:</strong> {{ object.updated }}</li>
        <li><strong>Total classifications:</strong> {{ object.classifications.count }}</li>
    </ul>
    {% if object.lightcurve_image %}
    <div><img src="{{object.lightcurve_image.url}}" style="width: 100%;"></div>
    {% endif %}
    <h3>Subjects</h3>
    <ul>
        {% for subject in object.zooniversesubject_set.all %}
        <li>{{ subject.subject_id }}&nbsp;&middot; {{ subject.annotation_count }} annotations (<a
                href="{{ subject.talk_url }}">Zooniverse Talk</a>)</li>
        {% empty %}
        <li>No subjects found.</li>
        {% endfor %}
    </ul>
</div>

<a href="{% url 'zooniverse:zooniversetarget_list' %}">Back to list</a>
{% endblock %}

zooniverse/templates/zooniverse/zooniversetarget_list.html
{% extends "tom_common/base.html" %}

{% block content %}
<h1>Zooniverse Target List</h1>

<form method="get">
    {{ target_lookup_form }}
    <input type="submit" value="Lookup">
</form>
<ul>
    {% for object in object_list %}
    <li>
        <a href="{% url 'zooniverse:zooniversetarget_detail' object.pk %}">
            {% if object.lightcurve_image %}
            <img src="{{object.lightcurve_image.url}}" style="width: 10%;">
            {% endif %}
            {{ object }}
        </a>
    </li>
    {% empty %}
    <li>No targets available.</li>
    {% endfor %}
</ul>


<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}